### PR TITLE
#166214085 Code coverage service

### PR DESCRIPTION
**Pull request by Nennyfills**
### Description
Integrate coveralls and codeclimate code coverage service

#### Type of change
- Install codeclimate-test-reporter and coveralls
- Add coveralls badge to readme.md file
- Add codeclimate badge to readme.md file
- Add coveralls-coveraget script
- Add codeclimate-coverage script
- Add coverage script

#### How Can This Been Tested?
N/A

#### Checklist:
N/A

#### Pivotal story
[#166214085](https://www.pivotaltracker.com/story/show/166214085)

#### Screenshots (if appropriate)
image

### CODE REVIEW

**Review by Lundii — COMMENTED** [review]
Great. I think you should edit the PR title to include the pivotal story ID.

**Review by Lundii — APPROVED** [review]
Looks great

**Review by Ukhu — COMMENTED** [review]
Good. But I think this chore is dependent on the completion of things like setting up the test framework (I think Korede is handling that) because it's after that one is completed that a script can be created which sends the coverage report to coveralls and then we can verify that the coveralls integration is successful.

**Comment by JuwonAbiola** [comment]
looks good

**Review by KvNGCzA — APPROVED** [review]
Good job. Get 2 others to approve this PR.

**Review by KvNGCzA — CHANGES_REQUESTED** [review]
Kindly rebase your branch with develop.

**Review by Ukhu — APPROVED** [review]

**Comment by Nennyfills** [comment]
> Kindly rebase your branch with develop.

> The branch is rebased.

**Review by Lundii — DISMISSED** [review]

**Review by Ukhu — DISMISSED** [review]

**Review by JuwonAbiola — DISMISSED** [review]

**Pull request closed without merging**
