### PR TITLE
#166214087 adds prettier and lint stage to the repo

### PR DESCRIPTION
**Pull request by Lundii**
#### Description
It sets up prettier and lint-stage to the repository. Prettier is added in collaboration with eslint
#### How can this be Tested?
* pull the branch to your local 
* use `npm install` to download all necessary packages
* download and enable prettier as an extension in your editor
* create a .js file and observe the rules being applied as you write codes in the file
* on `git commit` all staged files are checked to see they follow the specified rules
#### Checklist:
N/A
#### pivotal tracker story
https://www.pivotaltracker.com/story/show/166214087

### CODE REVIEW

**Review by Adekoreday — COMMENTED** [review]
good job new line required after closing braces in prettierrc

**Review by henryade — COMMENTED** [review]
i tried testing it, and its not flagging some of the stuff it should.

**Comment by KvNGCzA** [comment]
> i tried testing it, and its not flagging some of the stuff it should.

@henryade explain this better so he understands what's not working

**Comment by henryade** [comment]
> i tried testing it, and its not flagging some of the stuff it should.

i initialize a variable without declaration, i used var but later saw the rules in the .eslintrc.json file. i imported same thing twice and it didn't flag it.

**Review by Adekoreday — COMMENTED** [review]
i discovered it does  not automatically align/ formats the code on save i.e. make it prettier
 great work so far i think something is missing

**Comment by Lundii** [comment]
> i tried testing it, and its not flagging some of the stuff it should.

Oohh. I think i know why. Please download prettier extension and enable it then restart your editor

**Comment by Lundii** [comment]
> i discovered it does not automatically align/ formats the code on save i.e. make it prettier
> great work so far i think something is missing

Please download prettier extension for your editor and enable it, then restart your editor

**Comment by Lundii** [comment]
> > i tried testing it, and its not flagging some of the stuff it should.
> 
> @henryade explain this better so he understands what's not working

Yes. I think it's because they are yet to add prettier extension. I've informed them

**Comment by Lundii** [comment]
For some reason

**Comment by Lundii** [comment]
For some reason, this feature is no longer working as expected. I'm closing the PR to figure it out.

**Review by henryade — COMMENTED** [review]
Awesome. Your pivotal story should follow the new convention.

**Comment by Lundii** [comment]
> Awesome. Your pivotal story should follow the new convention.

**Comment by Lundii** [comment]
> > Awesome. Your pivotal story should follow the new convention.


This is an old PR. Before the new conventions was stated.

**Review by henryade — DISMISSED** [review]

**Comment by Adekoreday** [comment]
add instruction to enable _FORMAT ON SAVE in our development environment_ in how this PR can be tested nice one

**Comment by Lundii** [comment]
> add instruction to enable _FORMAT ON SAVE in our development environment_ in how this PR can be tested nice one

Can you please clarify this
for the prettier to work user needs to "enable format on save" i think you need to add it to instructions on how to test this PR

**Review by Ukhu — CHANGES_REQUESTED** [review]
You need to rebase this branch off the current develop.

**Comment by Lundii** [comment]
> You need to rebase this branch off the current develop.

Done

**Pull request closed without merging**
