### PR TITLE
  #166313415 create roles model 

### PR DESCRIPTION
**Pull request by JuwonAbiola**
#### What does this PR do?
Create roles model
#### Description of Task to be completed?
-create roles model
-create admin roles seeder file
-create patron roles seeder file
#### How should this be manually tested?
clone or download the project
checkout to ft-create-roles-model-166313415
git pull to get the latest update
npm i to install dependencies
create a database
run npm run db:roll to create table
run npm run db:seed to test the feature
#### Any background context you want to provide?
N/A
#### What are the relevant pivotal tracker stories?
[#166313415](https://www.pivotaltracker.com/n/projects/2350588/stories/166313415)

#### Screenshots (if appropriate)
N/A
#### Questions:
N/A

### CODE REVIEW

**Review by henryade — COMMENTED** [review]
Remove the equal to in your PR

**Comment by henryade** [comment]
> Remove the equal to in your PR

**Review by Lundii — CHANGES_REQUESTED** [review]
* Please remove the index.js file in the seeders folder as its empty. It causes an error when you run `npm run db:seed` 
* You have two commits. Make it 1
* server/database/config/config.js is listed as one as the files you changed Why is that

**Review by Lundii — COMMENTED** [review]
Please check your commits, they are 8

**Review by Lundii — COMMENTED** [review]
You now have 24 files changed. Please contact Bella, to show you how to resolve should in cae you are having dfficulties.

**Review by Adekoreday — COMMENTED** [review]
All files seem new can you clearify this

**Review by Ukhu — APPROVED** [review]

**Review by Ukhu — CHANGES_REQUESTED** [review]
rebase your branch with develop

**Review by henryade — APPROVED** [review]

**Review by Lundii — APPROVED** [review]
NIce work

**Review by Ukhu — APPROVED** [review]

**Review by KvNGCzA — APPROVED** [review]

**Pull request merged**
