### PR TITLE
#166214076 configure eslint 

### PR DESCRIPTION
**Pull request by allebd**
#### Description
Configure eslint

#### Type of change
- install eslint

#### How Has This Been Tested?
NA

#### Checklist:
NA

#### Pivotal Story
https://www.pivotaltracker.com/n/projects/2350588/stories/166214076

### CODE REVIEW

**Review by henryade — APPROVED** [review]
Good job

**Review by henryade — COMMENTED** [review]
In your PR, your pivotal story should have a link i.e [id](link)

**Review by Lundii — APPROVED** [review]
Good

**Review by KvNGCzA — APPROVED** [review]
Great job

**Review by Adekoreday — APPROVED** [review]
good

**Pull request merged**
