### PR TITLE
166214158 Search And Filter Functionality

### PR DESCRIPTION
**Pull request by Ukhu**
#### What does this PR do?
Implement search functionality based on optional filters

#### Description of Task to be completed?
  - create a route for searching books
  - create the controller for getting books
  - write tests for the route

#### How should this be manually tested?
 - pull this branch to your local repo
 - Run `npm run start:dev` on your command line
 - Open Postman and test the endpoint at `/api/v1/books` like that or using query parameters such as 'bookTitle', 'authorName', 'bookTag' and 'keyword'.

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#166214158](https://www.pivotaltracker.com/story/show/166214158)

#### Screenshots (if appropriate)
Screenshot (165)
Screenshot (164)
Screenshot (163)
Screenshot (167)
Screenshot (166)

#### Questions:
N/A

### CODE REVIEW

**Review by Adekoreday — CHANGES_REQUESTED** [review]
great job try and add write a test when the query keyword does not exist eg when user is supposed to do
authorName: and wrote author:  in the request query

**Review by Lundii — COMMENTED** [review]
Good job. So, I'm thinking, how is the search going to be implemented in the front end. I was thinking we will just have a search bar where the user can enter a book title, a book author or just some key words (related to the title, the author or the description). If this is the case then how exactly are the query parameter going to the added to the url?  I am probably thinking we would have something like a `api/v1/books?search=whatever` and the search in the database could follow as 
* search if a title equals to the query parameter, 
* search if an author equals the query parameter  and then
* search the author, title and book description if the query string is contained in any of them

**Comment by Ukhu** [comment]
> Good job. So, I'm thinking, how is the search going to be implemented in the front end. I was thinking we will just have a search bar where the user can enter a book title, a book author or just some key words (related to the title, the author or the description). If this is the case then how exactly are the query parameter going to the added to the url? I am probably thinking we would have something like a `api/v1/books?search=whatever` and the search in the database could follow as
> 
> * search if a title equals to the query parameter,
> * search if an author equals the query parameter  and then
> * search the author, title and book description if the query string is contained in any of them

Good question. So for the search bar, the url going to be used is `api/v1/books?keyword=whatever`. The keyword searches both the title, authorName and tags of all the books, so it will return the matching results. The other query params can be used on a page where the results are displayed for the user on the frontend, so they can filter results based on the authorName, bookTitle or Tag.

**Comment by Ukhu** [comment]
> great job try and add write a test when the query keyword does not exist eg when user is supposed to do
> authorName: and wrote author: in the request query

Technically, the user isn't going to be the one to enter the query param by themselves, they will just see a dropdown or something where they can choose from the already existing query params, e.g authorName, bookTitle etc. So that scenario of entering the wrong param will not occur.

It can only occur if it is done through PostMan or a similar app. If that's the case, the backend will simply perform the default operation of getting all the books in the database

**Pull request closed without merging**
