### PR TITLE
166325007 Create Followers Model

### PR DESCRIPTION
**Pull request by Ukhu**
#### What does this PR do?
Creates the followers model and implements relevant associations

#### Description of Task to be completed?
  - Create followers model
  - Add migration and seeder files
  - Implement associations

#### How should this be manually tested?
  - Pull this branch
  - Run **npm run db:rollback** in your console

#### Any background context you want to provide?
N/A

#### What are the relevant pivotal tracker stories?
[#166325007](https://www.pivotaltracker.com/story/show/166325007)

#### Screenshots (if appropriate)
N/A

#### Questions:
N/A

### CODE REVIEW

**Review by henryade — COMMENTED** [review]
You haven't rebase to  develop

**Comment by allebd** [comment]
No associations between users and followers id on users model

**Comment by Ukhu** [comment]
> You haven't rebase to develop

I have. Please check very well

**Comment by Ukhu** [comment]
> No associations between users and followers id on users model

Done

**Review by henryade — DISMISSED** [review]

**Review by JuwonAbiola — DISMISSED** [review]

**Review by allebd — DISMISSED** [review]
Good work

**Review by KvNGCzA — DISMISSED** [review]

**Review by Lundii — APPROVED** [review]

**Review by henryade — APPROVED** [review]

**Review by KvNGCzA — APPROVED** [review]

**Pull request merged**
