### PR TITLE
166214081 add hound badge to readme.md file

### PR DESCRIPTION
**Pull request by Lundii**
### Description
Adds hound batch to readme file
#### Type of change
N/A
#### How Has This Been Tested?
N/A
#### Checklist:
N/A
#### Pivotal story
https://www.pivotaltracker.com/story/show/166214081

### CODE REVIEW

**Comment by henryade** [comment]
Looks good

**Review by KvNGCzA — CHANGES_REQUESTED** [review]
Please fix your commit message according to the wiki. Also, kindly fix the spelling of badge in your PR title and branch name.

**Review by KvNGCzA — APPROVED** [review]
Good job. Get 3 others to approve this PR

**Review by Ukhu — APPROVED** [review]
Looks good

**Review by henryade — COMMENTED** [review]
good job

**Pull request merged**
